# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1c166b626db48919a8f9160d40dad7cd0c4a7958404815ce5a1258c2d2280908777fbcf6a765c1ffdb403d4a97af646acca252b842632d6ce565187fa8b1b1b

test:
  secret_key_base: 21fc7306d899aa988ebc97bda18a254d30475e68e032733f999c5e4817d4e035f81931d3797792a74c2938f82dce6be91ed6d54710f5264a22dd619d5c982daa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
